# Ce fichier docker-compose permet de gérer et démarrer plusieurs conteneurs
# nécessaires à l'application. Il facilite le lancement et l'arrêt de l'ensemble.

################################################################################
########################### SERVICES PRINCIPAUX ################################
################################################################################
services:
  mariadb:
    container_name: mariadb
    build:
      # Dossier où se trouve le Dockerfile
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        # Argument utilisé pendant la construction (pas au démarrage)
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    image: mariadb
    env_file:
      - .env
    expose:
      - 3306 # Port exposé uniquement entre conteneurs (pas sur l'hôte)
    volumes:
      - mariadb_volume:/var/lib/mysql
    healthcheck:
      # Vérifie si MariaDB répond avant que les autres services dépendent de lui
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - inception_network
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    depends_on:
      # Ce service attend que la base de données soit opérationnelle
      mariadb:
        condition: service_healthy
    build:
      context: ./requirements/wordpress
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    image: wordpress
    env_file:
      - .env
    expose:
      - 9000 # Port PHP-FPM interne
    volumes:
      - wordpress_volume:/var/www/html
    healthcheck:
      test: ["CMD", "sh", "-c", "[ -d /run/php ]"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - inception_network
    restart: on-failure

  nginx:
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        PATH_NGINX_CERTIFICATE: ${PATH_NGINX_CERTIFICATE}
        PATH_NGINX_TSL_KEY: ${PATH_NGINX_TSL_KEY}
    image: nginx
    ports:
      - 80:80   # HTTP -> redirection vers HTTPS
      - 443:443 # HTTPS
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_network
    restart: on-failure


################################################################################
############################### SERVICES BONUS #################################
################################################################################
  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/1_redis
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    image: redis
    env_file:
      - .env
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 1s
      retries: 10
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_network
    restart: always

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/2_ftp
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION}
    image: ftp
    env_file:
      - .env
    ports:
      - 20:20  # Données FTP
      - 21:21  # Commandes FTP
      - "21100-21110:21100-21110" # Ports passifs
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_network
    restart: on-failure
    
  static_website:
    container_name: static_website
    image: static-site:inception
    build: ./requirements/bonus/3_static_website
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - inception_network
    volumes:
      - static_html:/var/www/html

  adminer:
    container_name: adminer
    image: adminer:inception
    env_file:
        - .env
    build: 
        context: ./requirements/bonus/4_adminer
    restart: unless-stopped
    networks:
        - inception_network

    volumes:
        - adminer_data:/var/www/adminer
    ports:
        - "8090:80"

  cadvisor:
    container_name: cadvisor
    image: cadvisor:inception
    init: true
    build:
      context: ./requirements/bonus/5_cadvisor
      dockerfile: Dockerfile
    networks:
      - inception_network
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    
################################################################################
################################ VOLUMES #######################################
################################################################################

volumes:
  mariadb_volume:
    driver: local
    name: mariadb_volume
    driver_opts:
      type: none
      device: '/home/${USER}/data/mariadb'
      o: bind

  wordpress_volume:
    driver: local
    name: wordpress_volume
    driver_opts:
      type: none
      device: '/home/${USER}/data/wordpress'  
      o: bind
  
  static_html:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/static_html"
  adminer_data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: ${HOME}/data/adminer

################################################################################
################################ RESEAU ########################################
################################################################################
networks:
  inception_network:
    name: inception_network
    driver: bridge
